export type LabeledOption = {
  label: string; // Kullanıcıya gösterilen Türkçe metin
  value: string; // Sistem içinde kullanılacak İngilizce sabit
};

export type GroupedOptions = {
  group: string; // Grup başlığı (Türkçe)
  options: LabeledOption[];
};

// =====================
// TÜR GRUPLARI (GENRE)
// =====================

export const GENRE_GROUPS: GroupedOptions[] = [
  {
    group: "Animasyon",
    options: [
      { label: "Animasyon", value: "ANIMATION" },
    ],
  },
  {
    group: "Aksiyon & Macera",
    options: [
      { label: "Aksiyon & Macera", value: "ACTION & ADVENTURE" },
      { label: "Aksiyon Komedi", value: "ACTION COMEDY" },
      { label: "Aksiyon Gerilim", value: "ACTION THRILLER" },
      { label: "Çizgi Roman / Süper Kahramanlar", value: "COMIC BOOK & SUPER HEROES" },
      { label: "Dövüş Sanatları / Samuray", value: "MARTIAL ARTS/SAMURAI" },
      { label: "Romantik Macera", value: "ROMANTIC ADVENTURE" },
      { label: "Kılıç Şövalyeleri (Swashbuckler)", value: "SWASHBUCKLERS" },
      { label: "Kılıç & Sandalet (Tarihî Aksiyon)", value: "SWORD & SANDAL" },
      { label: "Savaş Macerası", value: "WAR ADVENTURE" },
    ],
  },
  {
    group: "Komedi",
    options: [
      { label: "Komedi", value: "COMEDY" },
      { label: "Komedi Gerilim", value: "COMEDY THRILLER" },
      { label: "Kara Komedi", value: "DARK COMEDY" },
      { label: "Dramatik Komedi", value: "DRAMATIC COMEDY" },
      { label: "Aile Komedisi", value: "FAMILY COMEDY" },
      { label: "Soygun / Kapkaç Komedisi", value: "HEIST/CAPER COMEDY" },
      { label: "Müzikal Komedi", value: "MUSICAL COMEDY" },
      { label: "Romantik Komedi", value: "ROMANTIC COMEDY" },
      { label: "Taşlama / Yergi", value: "SATIRE" },
      { label: "Bilimkurgu / Fantastik Komedi", value: "SCI-FI/FANTASY COMEDY" },
      { label: "Seks Komedisi", value: "SEX COMEDY" },
      { label: "Parodi / Spoof", value: "SPOOF/PARODY" },
      { label: "Spor Komedisi", value: "SPORTS COMEDY" },
    ],
  },
  {
    group: "Drama",
    options: [
      { label: "Drama", value: "DRAMA" },
      { label: "Macera Dramı", value: "ADVENTURE DRAMA" },
      { label: "Büyüme Hikâyesi (Coming-of-Age)", value: "COMING-OF-AGE" },
      { label: "Mahkeme Dramı", value: "COURTROOM DRAMA" },
      { label: "Suç Dramı", value: "CRIME DRAMA" },
      { label: "İnanç Temelli Drama", value: "FAITH-BASED DRAMA" },
      { label: "Aile Dramı", value: "FAMILY DRAMA" },
      { label: "Gangster Dramı", value: "GANGSTER" },
      { label: "Müzikal Drama", value: "MUSICAL DRAMA" },
      { label: "Dönem Dramı", value: "PERIOD DRAMA" },
      { label: "Politik Drama", value: "POLITICAL DRAMA" },
      { label: "Spor Dramı", value: "SPORTS DRAMA" },
      { label: "Savaş Dramı", value: "WAR DRAMA" },
      { label: "Savaş Destanı", value: "WAR EPIC" },
    ],
  },
  {
    group: "Aile",
    options: [
      { label: "Aile Filmi", value: "FAMILY" },
      { label: "Aile Macerası", value: "FAMILY ADVENTURE" },
      { label: "Çocuk Fantastiği", value: "KIDS' FANTASY" },
    ],
  },
  {
    group: "Korku",
    options: [
      { label: "Korku", value: "HORROR" },
      { label: "Uzaylı İstilası", value: "ALIEN INVASION" },
      { label: "Hayaletler & Perili Mekânlar", value: "GHOSTS & HAUNTS" },
      { label: "Gotik Korku", value: "GOTHIC HORROR" },
      { label: "Korku Komedi", value: "HORROR COMEDY" },
      { label: "Canavarlar", value: "MONSTERS" },
      { label: "Azgın Doğa / Doğa Felaketi Korkusu", value: "NATURE GONE WILD" },
      { label: "Okült / Gizemli Tarikatlar", value: "OCCULT" },
      { label: "Bilimkurgu Korku", value: "SCI-FI HORROR" },
      { label: "Kesip Biçenler & Psikopatlar", value: "SLASHERS & PSYCHOS" },
      { label: "Doğaüstü Gerilim", value: "SUPERNATURAL THRILLER" },
    ],
  },
  {
    group: "Gizem & Gerilim",
    options: [
      { label: "Gizem & Gerilim", value: "MYSTERY & SUSPENSE" },
      { label: "Suç Gerilimi", value: "CRIME THRILLER" },
      { label: "Dedektif Filmi", value: "DETECTIVE FILM" },
      { label: "Erotik Gerilim", value: "EROTIC THRILLER" },
      { label: "Kara Film (Film Noir)", value: "FILM NOIR" },
      { label: "Politik Gerilim", value: "POLITICAL THRILLER" },
      { label: "Psikolojik Gerilim", value: "PSYCHOLOGICAL THRILLER" },
      { label: "Bilimkurgu Gerilim", value: "SCI-FI THRILLER" },
      { label: "Casusluk", value: "SPY" },
      { label: "Savaş Zamanı Casusluğu", value: "WARTIME ESPIONAGE" },
    ],
  },
  {
    group: "Romantik",
    options: [
      { label: "Romantik", value: "ROMANCE" },
      { label: "Müzikal Romantizm", value: "MUSICAL ROMANCE" },
      { label: "Romantik Drama", value: "ROMANTIC DRAMA" },
      { label: "Romantik Destan", value: "ROMANTIC EPIC" },
      { label: "Romantik Fantastik", value: "ROMANTIC FANTASY" },
      { label: "Savaş Romantiği", value: "WAR ROMANCE" },
    ],
  },
  {
    group: "Bilimkurgu & Fantastik",
    options: [
      { label: "Bilimkurgu & Fantastik", value: "SCI-FI & FANTASY" },
      { label: "Mitolojik", value: "MYTHOLOGICAL" },
      { label: "Prehistorik Fantastik", value: "PREHISTORIC FANTASY" },
      { label: "Psikolojik Bilimkurgu", value: "PSYCHOLOGICAL SCI-FI" },
      { label: "Bilimkurgu Felaket Filmi", value: "SCI-FI DISASTER FILMS" },
      { label: "Kılıç ve Büyü", value: "SWORD AND SORCERY" },
    ],
  },
  {
    group: "Western",
    options: [
      { label: "Western", value: "WESTERN" },
      { label: "Komedi Western", value: "COMEDY WESTERN" },
      { label: "Epik Western", value: "EPIC WESTERN" },
      { label: "Modern Western", value: "MODERN WESTERN" },
    ],
  },
];

// ======================
// ETİKET GRUPLARI (TAGS)
// ======================

export const TAG_GROUPS: GroupedOptions[] = [
  {
    group: "Aksiyon",
    options: [
      { label: "Hava Aksiyonu (Uçak vb.)", value: "AERIAL ACTION" },
      { label: "Araba Takibi", value: "CAR CHASE" },
      { label: "Silahlı Dövüş (Kılıç/Bıçak)", value: "COMBAT WITH WEAPONS (SWORDS/KNIVES)" },
      { label: "Yakın Dövüş", value: "HAND TO HAND COMBAT" },
      { label: "Dövüş Sanatları", value: "MARTIAL ARTS" },
      { label: "Silahlı Şiddet", value: "GUN VIOLENCE" },
      { label: "Absürt / Komik Aksiyon", value: "SILLY ACTION" },
      { label: "Şiddet", value: "VIOLENCE" },
      { label: "Araba Kazası", value: "CAR CRASH" },
      { label: "Uzay Aksiyonu / Uzay Operası", value: "SPACE ACTION/OPERA" },
    ],
  },
  {
    group: "Uyarlama",
    options: [
      { label: "Makale Uyarlaması", value: "ARTICLE ADAPTATION" },
      { label: "Grafik Roman Uyarlaması", value: "GRAPHIC NOVEL ADAPTATION" },
      { label: "Kurgu Dışı Kitap Uyarlaması", value: "NONFICTION BOOK ADAPTATION" },
      { label: "Roman Uyarlaması", value: "NOVEL ADAPTATION" },
      { label: "TV Dizisi Uyarlaması", value: "TELEVISION SERIES ADAPTATION" },
      { label: "Gerçek Olaydan Uyarlama", value: "BASED ON TRUE EVENT" },
      { label: "Video Oyunu Uyarlaması", value: "VIDEO GAME ADAPTATION" },
      { label: "Oyun / Opera / Müzikal Uyarlaması", value: "PLAY/OPERA/MUSICAL ADAPTATION" },
      { label: "Kısa Hikâye Uyarlaması", value: "SHORT STORY ADAPTATION" },
    ],
  },
  {
    group: "Alternatif Dünyalar & Uzay",
    options: [
      { label: "Kıyamet Sonrası (Post-Apokaliptik)", value: "POST-APOCALYPTIC" },
      { label: "Alternatif Evren", value: "ALTERNATE UNIVERSE" },
      { label: "Ay", value: "MOON" },
      { label: "Mars", value: "MARS" },
      { label: "Çoklu Evren (Multiverse)", value: "MULTIVERSE" },
      { label: "Uzaylı / Uzak Gezegen / Galaksi", value: "ALIEN/DISTANT PLANET/GALAXY" },
      { label: "Uzak Gezegen / Galaksi", value: "DISTANT PLANET/GALAXY" },
      { label: "Uzay Gemileri / Uzay Yolculuğu", value: "SPACESHIPS/SPACE TRAVEL" },
      { label: "Zaman Yolculuğu", value: "TIME TRAVEL" },
    ],
  },
  {
    group: "Hayvan Krallığı",
    options: [
      { label: "Hayvanlar", value: "ANIMALS" },
      { label: "İnsansı Hayvan (Antropomorfik)", value: "ANTHROPOMORPHIC ANIMAL" },
      { label: "Kuşlar", value: "BIRDS" },
      { label: "Kediler", value: "CATS" },
      { label: "Köpekler", value: "DOGS" },
      { label: "Atlar", value: "HORSES" },
      { label: "Evcil Hayvanlar", value: "PETS" },
    ],
  },
  {
    group: "Mitoloji / Dayandığı Kaynak",
    options: [
      { label: "Afrika Mitolojisi", value: "AFRICAN MYTHOLOGY" },
      { label: "Amerikan Halk Hikâyeleri", value: "AMERICAN FOLKLORE" },
      { label: "Yunan / İskandinav / Roma Mitolojisi", value: "GREEK/NORSE/ROMAN MYTHOLOGY" },
      { label: "Yerli / Yerli Halk Mitolojisi", value: "NATIVE/INDIGENOUS MYTHOLOGY" },
    ],
  },
  {
    group: "Bütçe",
    options: [
      { label: "Ultra Düşük Bütçe", value: "ULTRA LOW BUDGET" },
      { label: "Düşük Bütçe", value: "LOW BUDGET" },
      { label: "Orta Bütçe", value: "MEDIUM BUDGET" },
      { label: "Yüksek Bütçe", value: "HIGH BUDGET" },
    ],
  },
  {
    group: "Karakterler",
    options: [
      { label: "Mazlum / Ezilen Kahraman (Underdog)", value: "UNDERDOG" },
      { label: "Anti-Kahraman", value: "ANTIHERO" },
      { label: "Sporcular", value: "ATHLETES" },
      { label: "Çocuk / Çocuklar", value: "CHILD/CHILDREN" },
      { label: "Doktor", value: "DOCTOR" },
      { label: "Uyuşturucu Satıcısı", value: "DRUG DEALER" },
      { label: "Düşmüş Kahraman", value: "FALLEN HERO" },
      { label: "Femme Fatale", value: "FEMME FATALE" },
      { label: "Tarihî Kişilik", value: "HISTORICAL FIGURE" },
      { label: "Gazeteci", value: "JOURNALIST" },
      { label: "Kontrolsüz Tip (Loose Cannon)", value: "LOOSE CANNON" },
      { label: "Görevdeki Kişi", value: "PERSON ON A MISSION" },
      { label: "Tehlikede Kişi", value: "PERSON IN PERIL" },
      { label: "Adsız Kişi", value: "PERSON WITH NO NAME" },
      { label: "Dışlanmış / Dışarıdan Gelen", value: "OUTCAST/OUTSIDER" },
      { label: "Polis", value: "POLICE" },
      { label: "Bilim İnsanı", value: "SCIENTIST" },
      { label: "Asker", value: "SOLDIER" },
      { label: "Gizli Polis", value: "UNDERCOVER COP" },
      { label: "Bilge Yaşlı Kişi", value: "WISE OLD PERSON" },
      { label: "Yazar / Senarist", value: "WRITER/SCREENWRITER" },
      { label: "Dev Canavar", value: "GIANT MONSTER" },
      { label: "Canavar", value: "MONSTER" },
      { label: "Vampir", value: "VAMPIRE" },
      { label: "Kurtadam", value: "WEREWOLF" },
      { label: "Zombi", value: "ZOMBIE" },
      { label: "Kaçak / Kaçan Kişi", value: "PERSON ON THE RUN" },
      { label: "Öğrenci", value: "STUDENT" },
      { label: "50+ Yaşında Başkarakter", value: "PROTAGONIST OVER 50" },
      { label: "Oyuncu / Ünlü", value: "ACTOR/CELEBRITY" },
      { label: "Kadın Kötü Karakter", value: "FEMALE VILLAIN" },
      { label: "Yaratık", value: "CREATURE" },
      { label: "Kötü Deha", value: "EVIL GENIUS" },
      { label: "Nazi", value: "NAZI" },
      { label: "Suikastçı", value: "ASSASSIN" },
      { label: "Zorba", value: "BULLY" },
      { label: "Askerî Kötü Karakter", value: "MILITARY VILLAIN" },
      { label: "İsteksiz Kahraman", value: "RELUCTANT HERO" },
      { label: "Asker Emeklisi / Gazisi", value: "MILITARY VETERAN" },
      { label: "Kendi Kendisinin Düşmanı", value: "OWN WORST ENEMY" },
      { label: "İş İnsanı", value: "BUSINESS PERSON" },
      { label: "İblis", value: "DEMON" },
      { label: "Uzaylı", value: "ALIEN" },
      { label: "Terörist", value: "TERRORIST" },
      { label: "Seri Katil", value: "SERIAL KILLER" },
      { label: "Avukatlar", value: "LAWYERS" },
      { label: "Hayalet", value: "GHOST" },
      { label: "Siyasetçi", value: "POLITICIAN" },
      { label: "Zaman Yolcusu", value: "TIME-TRAVELER" },
      { label: "Robot", value: "ROBOT" },
      { label: "Yozlaşmış Yetkili", value: "CORRUPT OFFICIAL" },
      { label: "Yazar", value: "AUTHOR" },
      { label: "Tarihçi", value: "HISTORIAN" },
      { label: "Kütüphaneci", value: "LIBRARIAN" },
      { label: "Eğitimci", value: "EDUCATOR" },
      { label: "Pilot", value: "PILOT" },
      { label: "Koç / Antrenör", value: "COACH" },
    ],
  },
  {
    group: "Çatışma Türü",
    options: [
      { label: "Başkarakter vs Doğa", value: "PROTAGONIST VS NATURE" },
      { label: "Başkarakter vs Teknoloji", value: "PROTAGONIST VS TECHNOLOGY" },
      { label: "Başkarakter vs Antagonist", value: "PROTAGONIST VS ANTAGONIST" },
      { label: "Başkarakter vs Kendisi", value: "PROTAGONIST VS THEMSELF" },
    ],
  },
  {
    group: "Suç & Suçlular",
    options: [
      { label: "Kundaklama / Kundakçı", value: "ARSON/ARSONIST" },
      { label: "Sanat Sahteciliği", value: "ART FORGERY" },
      { label: "Şantaj", value: "BLACKMAIL" },
      { label: "Üçkâğıtçı", value: "CON ARTIST" },
      { label: "Komplo / Üstünü Örtme", value: "CONSPIRACY/COVER-UP" },
      { label: "Casusluk", value: "ESPIONAGE" },
      { label: "Dolandırıcılık", value: "FRAUD" },
      { label: "Soygun", value: "HEIST" },
      { label: "Rehine Durumu", value: "HOSTAGE SITUATION" },
      { label: "İnsan Kaçakçılığı", value: "HUMAN TRAFFICKING" },
      { label: "Organize Suç", value: "ORGANIZED CRIME" },
      { label: "Kayıp Kişi", value: "MISSING PERSON" },
      { label: "Tecavüz / Tecavüzcü", value: "RAPE/RAPIST" },
      { label: "Kaçakçılık / Kaçakçı", value: "SMUGGLING/SMUGGLER" },
      { label: "Takipçi / Saplantılı Takip", value: "STALKER" },
      { label: "Hırsızlık / Soygun", value: "THEFT/ROBBERY" },
      { label: "Soykırım", value: "GENOCIDE" },
      { label: "Süper Kötü", value: "SUPERVILLAIN" },
      { label: "Çeteler / Çete Üyeleri / Gangster", value: "GANGS/GANG MEMBERS/GANGSTER" },
      { label: "Cinayet / Katil", value: "MURDER/MURDERER" },
      { label: "Cinsel Saldırı / Taciz", value: "SEXUAL ASSAULT/SEXUAL HARASSMENT" },
      { label: "Kaçırma / Kaçıran Kişi", value: "ABDUCTION/KIDNAPPING/KIDNAPPER" },
    ],
  },
  {
    group: "Felaket",
    options: [
      { label: "Deprem", value: "EARTHQUAKE" },
      { label: "Sel", value: "FLOOD" },
      { label: "Kasırga / Fırtına", value: "HURRICANE" },
      { label: "Meteor", value: "METEOR" },
      { label: "Doğal Afet", value: "NATURAL DISASTER" },
      { label: "Tornado / Hortum", value: "TORNADO" },
      { label: "Volkan", value: "VOLCANO" },
      { label: "Kıyamet / Dünyanın Sonu", value: "APOCALYPSE" },
      { label: "Nükleer Felaket", value: "NUCLEAR DISASTER" },
      { label: "Teknolojik Saldırı", value: "TECHNOLOGICAL ATTACK" },
      { label: "Terör Saldırısı", value: "TERRORIST ATTACK" },
    ],
  },
  {
    group: "Duygusal Haller",
    options: [
      { label: "Kâbus", value: "NIGHTMARE" },
      { label: "Kabul", value: "ACCEPTANCE" },
      { label: "Yabancılaşma", value: "ALIENATION" },
      { label: "Şefkat", value: "COMPASSION" },
      { label: "Kültür Şoku", value: "CULTURE SHOCK" },
      { label: "Aldatma / Yanıltma", value: "DECEPTION" },
      { label: "Kıskançlık / Haset", value: "ENVY/JEALOUSY" },
      { label: "Korku", value: "FEAR" },
      { label: "Aşk", value: "LOVE" },
      { label: "Güven", value: "TRUST" },
      { label: "Aşk Her Şeyi Yener", value: "LOVE CONQUERS ALL" },
      { label: "Takıntı / Obsesyon", value: "OBSESSION" },
      { label: "Neşe", value: "JOY" },
    ],
  },
  {
    group: "Korku Alt Türleri",
    options: [
      { label: "Vücut Korkusu (Body Horror)", value: "BODY HORROR" },
      { label: "Gore / Kanlı Şiddet", value: "GORE" },
      { label: "Slasher", value: "SLASHER" },
      { label: "İşkence", value: "TORTURE" },
      { label: "Perili Ev", value: "HAUNTED HOUSE" },
    ],
  },
  {
    group: "Hastalık & Ruh Sağlığı",
    options: [
      { label: "Madde Bağımlılığı", value: "DRUG ADDICTION/SUBSTANCE USE DISORDER" },
      { label: "Alkolizm", value: "ALCOHOLISM" },
      { label: "Kanser", value: "CANCER" },
      { label: "Depresyon", value: "DEPRESSION" },
      { label: "Hastalık", value: "ILLNESS" },
      { label: "Ruh Sağlığı Bozukluğu / Sıkıntısı", value: "MENTAL HEALTH DISORDER/DISTRESS" },
      { label: "Travma Sonrası Stres (TSSB)", value: "PTSD" },
      { label: "İntihar", value: "SUICIDE" },
      { label: "Hafıza Kaybı", value: "MEMORY LOSS" },
      { label: "Halüsinasyonlar", value: "HALLUCINATIONS" },
      { label: "Terminal Hastalık", value: "TERMINAL ILLNESS" },
    ],
  },
  {
    group: "İkonik Mekanlar",
    options: [
      { label: "Vatikan", value: "THE VATICAN" },
      { label: "Central Park – Gölet (The Pond)", value: "THE POND – CENTRAL PARK" },
      { label: "Özgürlük Heykeli", value: "STATUE OF LIBERTY" },
    ],
  },
  {
    group: "Hayat Olayları & Kutlamalar",
    options: [
      { label: "Bekârlığa Veda Partisi", value: "BACHELORETTE/BACHELOR PARTY" },
      { label: "Doğum Günü", value: "BIRTHDAY" },
      { label: "Doğum", value: "CHILDBIRTH" },
      { label: "Cenaze", value: "FUNERAL" },
      { label: "Mezuniyet", value: "GRADUATION" },
      { label: "Balo (Prom)", value: "PROM" },
      { label: "Buluşma / Reunion", value: "REUNION" },
      { label: "Düğün", value: "WEDDING" },
      { label: "Noel", value: "CHRISTMAS" },
      { label: "Paskalya", value: "EASTER" },
      { label: "Seçim Günü", value: "ELECTION DAY" },
      { label: "Sonbahar", value: "AUTUMN" },
      { label: "Cadılar Bayramı (Halloween)", value: "HALLOWEEN" },
      { label: "Hanuka", value: "HANUKKAH" },
      { label: "Tatil / Bayram Dönemi", value: "HOLIDAY" },
      { label: "Yılbaşı", value: "NEW YEAR'S" },
      { label: "Ramazan", value: "RAMADAN" },
      { label: "İlkbahar", value: "SPRING" },
      { label: "Yaz", value: "SUMMER" },
      { label: "Şükran Günü (Thanksgiving)", value: "THANKSGIVING" },
      { label: "ABD Bağımsızlık Günü / 4 Temmuz", value: "US INDEPENDENCE DAY/JULY 4" },
      { label: "Sevgililer Günü", value: "VALENTINE'S DAY" },
      { label: "Kış", value: "WINTER" },
      { label: "Parti", value: "PARTY" },
      { label: "Evlilik Teklifi", value: "MARRIAGE PROPOSAL" },
      { label: "Tatil / Seyahat", value: "VACATION" },
    ],
  },
  {
    group: "Hayat Deneyimleri & Dönüşümler",
    options: [
      { label: "Bağımlılık", value: "ADDICTION" },
      { label: "Yoksulluk", value: "POVERTY" },
      { label: "Üst Sınıf", value: "UPPER CLASS" },
      { label: "İşçi Sınıfı", value: "WORKING CLASS" },
      { label: "Hayal Kırıklığı / Gözünün Açılması", value: "DISILLUSIONMENT" },
      { label: "Dişilik / Feminenlik", value: "FEMININITY" },
      { label: "Toplumsal Cinsiyet", value: "GENDER" },
      { label: "Masumiyetin Kaybı", value: "LOSS OF INNOCENCE" },
      { label: "Erillik / Maskülenlik", value: "MASCULINITY" },
      { label: "Nostalji", value: "NOSTALGIA" },
      { label: "Yeniden Doğuş", value: "REBIRTH" },
      { label: "Kefaret / Arınma", value: "REDEMPTION" },
      { label: "İntikam", value: "REVENGE" },
      { label: "Devrim", value: "REVOLUTION" },
      { label: "Kendini Feda Etme", value: "SELF SACRIFICE" },
      { label: "Mücadele", value: "STRUGGLE" },
      { label: "Ergenlik Dönemi", value: "ADOLESCENCE" },
      { label: "Çocukluk", value: "CHILDHOOD" },
      { label: "Orta Yaş Krizi", value: "MIDLIFE CRISIS" },
      { label: "Hamilelik", value: "PREGNANCY" },
      { label: "Ergenliğe Giriş (Puberte)", value: "PUBERTY" },
      { label: "Çeyrek Yaş Krizi (20’ler Krizi)", value: "QUARTERLIFE CRISIS" },
      { label: "Gelir Eşitsizliği", value: "INCOME INEQUALITY" },
      { label: "Büyüme Hikâyesi (Coming of Age)", value: "COMING OF AGE" },
      { label: "Dolaptan Çıkma / Açılma", value: "COMING OUT OF THE CLOSET" },
      { label: "Irk İlişkileri / Irkçılık", value: "RACE RELATIONS/RACISM" },
      { label: "Ölüm / Yas / Kayıp", value: "DEATH/GRIEF/LOSS" },
      { label: "Geniş Cinsiyet Kimliği", value: "GENDER EXPANSIVE" },
      { label: "Cinsiyet Akışkanlığı", value: "GENDER FLUIDITY" },
    ],
  },
  {
    group: "Askerî & Savaş",
    options: [
      { label: "ABD – Afganistan – Irak Çatışması", value: "US-AFGHANISTAN-IRAQ CONFLICT" },
      { label: "İç Savaş", value: "CIVIL WAR" },
      { label: "Emperyalizm", value: "IMPERIALISM" },
      { label: "ABD Bağımsızlık Savaşı", value: "US REVOLUTIONARY WAR" },
      { label: "Özel Kuvvetler", value: "SPECIAL FORCES" },
      { label: "Vietnam Savaşı", value: "VIETNAM WAR" },
      { label: "Savaş", value: "WAR" },
      { label: "1. Dünya Savaşı", value: "WORLD WAR I" },
      { label: "2. Dünya Savaşı", value: "WORLD WAR II" },
      { label: "3. Dünya Savaşı", value: "WORLD WAR III" },
      { label: "Savaş Cehennemdir", value: "WAR IS HELL" },
      { label: "Soykırım", value: "GENOCIDE" },
    ],
  },
  {
    group: "Ahlak & Değerler",
    options: [
      { label: "Otorite", value: "AUTHORITY" },
      { label: "Güzellik", value: "BEAUTY" },
      { label: "Uzlaşma", value: "COMPROMISE" },
      { label: "Cesaret", value: "COURAGE" },
      { label: "İnanç", value: "FAITH" },
      { label: "Açgözlülük", value: "GREED" },
      { label: "Suçluluk / Pişmanlık", value: "GUILT/REGRET" },
      { label: "Onur / Dürüstlük", value: "HONOR/INTEGRITY" },
      { label: "Adalet / Adaletsizlik", value: "JUSTICE/INJUSTICE" },
      { label: "Şehitlik", value: "MARTYRDOM" },
      { label: "Merhamet / Lütuf", value: "MERCY/GRACE" },
      { label: "Kibir / Gösteriş", value: "VANITY" },
      { label: "İyi vs Kötü", value: "GOOD VS EVIL" },
      { label: "Yozlaşma", value: "CORRUPTION" },
      { label: "Kötülük", value: "EVIL" },
      { label: "İlham Verici", value: "INSPIRATIONAL" },
    ],
  },
  {
    group: "Yaş Sınıflandırmaları",
    options: [
      { label: "Genel İzleyici (G / U)", value: "RATED G/U" },
      { label: "NC-17 / 18", value: "RATED NC-17/18" },
      { label: "PG", value: "RATED PG" },
      { label: "PG-13 / 12", value: "RATED PG-13/12" },
      { label: "R / 15", value: "RATED R/15" },
    ],
  },
  {
    group: "Müzik",
    options: [
      { label: "Klasik Müzik", value: "CLASSICAL" },
      { label: "Country", value: "COUNTRY (MUSIC)" },
      { label: "Elektronik Müzik", value: "ELECTRONIC" },
      { label: "Hip Hop", value: "HIP HOP" },
      { label: "Caz", value: "JAZZ" },
      { label: "Opera", value: "OPERA" },
      { label: "Rock’n Roll", value: "ROCK N ROLL" },
      { label: "Blues", value: "BLUES (MUSIC)" },
    ],
  },
  {
    group: "Anlatı Yapısı",
    options: [
      { label: "Kaçış Hikâyesi", value: "ESCAPE" },
      { label: "Kahramanın Yolculuğu", value: "HERO'S JOURNEY" },
      { label: "Hac / Yolculuk (Pilgrimage)", value: "PILGRIMAGE" },
      { label: "Kurtarma Hikâyesi", value: "RESCUE" },
      { label: "Yol Filmi / Road Trip", value: "ROAD TRIP" },
      { label: "Gizli Görev", value: "SECRET MISSION" },
      { label: "Evi Bulmak / Eve Dönüş", value: "FINDING HOME/RETURNING HOME" },
      { label: "Takip / Kovalamaca", value: "PURSUIT" },
    ],
  },
  {
    group: "Organizasyonlar",
    options: [
      { label: "İstihbarat Kurumları (CIA/NSA/MI6)", value: "CIA/NSA/M16" },
      { label: "FBI", value: "FBI" },
      { label: "Gizli Servis", value: "SECRET SERVICE" },
      { label: "Gizli Toplum / Tarikat", value: "SECRET SOCIETY" },
      { label: "Casusluk", value: "SPY" },
      { label: "Yeraltı Organizasyonu", value: "UNDERGROUND ORGANIZATION" },
      { label: "Kıyamet Tarikatı", value: "DOOMSDAY CULT" },
      { label: "Federal Hükümet", value: "FEDERAL GOVERNMENT" },
    ],
  },
  {
    group: "Kişisel Gelişim & Kimlik",
    options: [
      { label: "Yaşlanma", value: "AGING" },
      { label: "Güçlenme / Güçlenme Hikâyeleri", value: "EMPOWERMENT" },
      { label: "Umut / Umutsuzluk", value: "HOPE/HOPELESSNESS" },
      { label: "Alçakgönüllülük", value: "HUMILITY" },
      { label: "Kimlik / Bireysellik", value: "IDENTITY/INDIVIDUALITY" },
      { label: "Olgunlaşma", value: "MATURITY" },
      { label: "Kendini Keşfetme", value: "SELF-DISCOVERY" },
      { label: "Hırs / Ambisyon", value: "AMBITION" },
      { label: "Kişisel Gelişim / Self-Help", value: "SELF-HELP" },
      { label: "Hayatta Kalma", value: "SURVIVAL" },
    ],
  },
  {
    group: "Siyaset",
    options: [
      { label: "ABD Hükümeti", value: "US GOVERNMENT" },
      { label: "Muhafazakâr Siyaset", value: "CONSERVATIVE POLITICS" },
      { label: "Çevre / İklim Aktivizmi", value: "ENVIRONMENTAL/CLIMATE ADVOCACY" },
      { label: "Feminist", value: "FEMINIST" },
      { label: "Liberal Siyaset", value: "LIBERAL POLITICS" },
      { label: "Toplumsal Yorum / Eleştiri", value: "SOCIAL COMMENTARY" },
      { label: "Hükümet Komplosu", value: "GOVERNMENT CONSPIRACY" },
      { label: "Sivil Haklar", value: "CIVIL RIGHTS" },
      { label: "İlerici Siyaset", value: "PROGRESSIVE POLITICS" },
    ],
  },
  {
    group: "Başroller (Yaş)",
    options: [
      { label: "Kadın Başrol (<13)", value: "FEMALE (<13)" },
      { label: "Kadın Başrol (13-18)", value: "FEMALE (13-18)" },
      { label: "Kadın Başrol (19-24)", value: "FEMALE (19-24)" },
      { label: "Kadın Başrol (25-34)", value: "FEMALE (25-34)" },
      { label: "Kadın Başrol (35-44)", value: "FEMALE (35-44)" },
      { label: "Kadın Başrol (45-54)", value: "FEMALE (45-54)" },
      { label: "Kadın Başrol (55-64)", value: "FEMALE (55-64)" },
      { label: "Kadın Başrol (>65)", value: "FEMALE (>65)" },
      { label: "Erkek Başrol (<13)", value: "MALE (<13)" },
      { label: "Erkek Başrol (13-18)", value: "MALE (13-18)" },
      { label: "Erkek Başrol (19-24)", value: "MALE (19-24)" },
      { label: "Erkek Başrol (25-34)", value: "MALE (25-34)" },
      { label: "Erkek Başrol (35-44)", value: "MALE (35-44)" },
      { label: "Erkek Başrol (45-54)", value: "MALE (45-54)" },
      { label: "Erkek Başrol (55-64)", value: "MALE (55-64)" },
      { label: "Erkek Başrol (>65)", value: "MALE (>65)" },
    ],
  },
  {
    group: "Başroller (Kimlik & Kadro)",
    options: [
      {
        label: "Gelişimsel Engelli Başkarakter",
        value: "PROTAGONIST WITH DEVELOPMENTAL DISABILITIES",
      },
      {
        label: "Fiziksel Engelli Başkarakter",
        value: "PROTAGONIST WITH PHYSICAL DISABILITIES",
      },
      { label: "Göçmen Başkarakter", value: "IMMIGRANT PROTAGONIST" },
      { label: "Bechdel Testini Geçiyor", value: "PASSES BECHDEL TEST" },
      { label: "Kadın Başkarakter", value: "FEMALE PROTAGONIST" },
      { label: "Siyahî Başkarakter", value: "BLACK PROTAGONIST" },
      {
        label: "Asyalı / Pasifik Adalı Başkarakter",
        value: "ASIAN OR PACIFIC ISLANDER PROTAGONIST",
      },
      { label: "Yerli Amerikan Başkarakter", value: "NATIVE AMERICAN PROTAGONIST" },
      { label: "Kapsayıcı Kadro", value: "INCLUSIVE CAST" },
      { label: "Tamamen Kadın Kadro", value: "ALL-FEMALE ENSEMBLE" },
      {
        label: "Trans / Geniş Cinsiyetli Başkarakter",
        value: "TRANSGENDER/GENDER EXPANSIVE PROTAGONIST",
      },
      { label: "Ortadoğulu Başkarakter", value: "MIDDLE EASTERN PROTAGONIST" },
      { label: "LGBTQ+ Başkarakter", value: "LGBTQ+ PROTAGONIST" },
      { label: "Engelli Başkarakter", value: "DISABLED PROTAGONIST" },
      { label: "Vito Russo Testini Geçiyor", value: "PASSES VITO RUSSO TEST" },
      { label: "Yerli / Yerli Halk Başkarakter", value: "INDIGENOUS PROTAGONIST" },
      { label: "Yahudi Başkarakter", value: "JEWISH PROTAGONIST" },
      { label: "Latin Başkarakter", value: "LATINO/LATINA PROTAGONIST" },
      { label: "Asker Emeklisi Başkarakter", value: "MILITARY VETERAN PROTAGONIST" },
    ],
  },
  {
    group: "İlişkiler",
    options: [
      { label: "Anneler / Annelik", value: "MOTHERS/MOTHERHOOD" },
      { label: "Tek Ebeveyn", value: "SINGLE PARENT" },
      { label: "İstismar", value: "ABUSE" },
      { label: "İhanet", value: "BETRAYAL" },
      { label: "Patron – Çalışan", value: "BOSS-EMPLOYEE" },
      { label: "Flört / Çıkma", value: "DATING" },
      { label: "Boşanma", value: "DIVORCE" },
      { label: "İlk Buluşma", value: "FIRST DATE" },
      { label: "Arkadaşlık", value: "FRIENDSHIP" },
      { label: "Aşk Üçgeni", value: "LOVE TRIANGLE" },
      { label: "Evlilik", value: "MARRIAGE" },
      { label: "Tesadüfi Tatlı Karşılaşma (Meet-Cute)", value: "MEET-CUTE" },
      { label: "Kardeşler / Kardeşlik", value: "SIBLINGS/SIBLINGHOOD" },
      { label: "Öğretmen – Öğrenci", value: "TEACHER/STUDENT" },
      { label: "Topluluk / Komşuluk", value: "COMMUNITY" },
      { label: "Ayrılık", value: "BREAKUP" },
      { label: "Büyük Ebeveynler (Dede / Nine)", value: "GRANDPARENTS" },
      { label: "Ev Arkadaşları", value: "ROOMMATES" },
      { label: "Eski Partner", value: "EX-PARTNER" },
      { label: "Suç Ortakları", value: "PARTNERS-IN-CRIME" },
      { label: "Barışma / Yeniden Bir Araya Gelme", value: "RECONCILIATION" },
      { label: "Affetme", value: "FORGIVENESS" },
      { label: "Komşular", value: "NEIGHBORS" },
      { label: "Baba – Oğul İlişkisi", value: "FATHER/SON RELATIONSHIP" },
      { label: "İş Arkadaşları", value: "COWORKERS" },
      { label: "Anne – Oğul İlişkisi", value: "MOTHER/SON RELATIONSHIP" },
      { label: "Baba – Kız İlişkisi", value: "FATHER/DAUGHTER RELATIONSHIP" },
      { label: "Anne – Kız İlişkisi", value: "MOTHER/DAUGHTER RELATIONSHIP" },
      { label: "Yasak Aşk", value: "FORBIDDEN LOVE" },
      { label: "Husumet / Kan Davası", value: "FEUD" },
      { label: "Aldatma / Sadakatsizlik", value: "ADULTERY/INFIDELITY" },
      { label: "Babalar / Babalık", value: "FATHERS/FATHERHOOD" },
      { label: "Kardeşler / Erkek Kardeşlik", value: "BROTHERS/BROTHERHOOD" },
      { label: "Kız Kardeşler / Kız Kardeşlik", value: "SISTERS/SISTERHOOD" },
    ],
  },
  {
    group: "Din & Maneviyat",
    options: [
      { label: "İncil / Kutsal Kitap", value: "BIBLICAL/BIBLE" },
      { label: "Budizm", value: "BUDDHISM" },
      { label: "Hristiyanlık", value: "CHRISTIANITY" },
      { label: "Kültler / Tarikatlar", value: "CULTS" },
      { label: "Hinduizm", value: "HINDUISM" },
      { label: "İslam", value: "ISLAM" },
      { label: "Paranormal / Okült", value: "PARANORMAL/OCCULT" },
      { label: "Peygamberler / Kehanet", value: "PROPHETS/PROPHECY" },
      { label: "Protestanlık", value: "PROTESTANTISM" },
      { label: "Din", value: "RELIGION" },
      { label: "Sihizm", value: "SIKHISM" },
      { label: "Taoizm", value: "TAOISM" },
      { label: "Vudu", value: "VOODOO" },
      { label: "Wicca", value: "WICCA" },
      { label: "Tanrılar / Tanrıçalar", value: "GODS/GODDESSES" },
      { label: "Şeytan", value: "SATAN/THE DEVIL" },
      { label: "Katoliklik", value: "CATHOLICISM" },
      { label: "Yahudilik", value: "JEWISH/JUDAISM" },
    ],
  },
  {
    group: "Bilim & Teknoloji",
    options: [
      { label: "Yapay Zekâ", value: "ARTIFICIAL INTELLIGENCE" },
      { label: "Bilgisayarlar", value: "COMPUTERS" },
      { label: "Hastalık Salgını / Epidemi", value: "DISEASE EPIDEMIC" },
      { label: "Genetik / Mutasyonlar", value: "GENETICS/MUTATIONS" },
      { label: "Tıbbi Araştırma", value: "MEDICAL RESEARCH" },
      { label: "Sanal Gerçeklik", value: "VIRTUAL REALITY" },
      { label: "Sosyal Medya", value: "SOCIAL MEDIA" },
      { label: "Uzay Gemisi", value: "SPACESHIP" },
    ],
  },
  {
    group: "Spor & Oyunlar",
    options: [
      { label: "Beyzbol", value: "BASEBALL" },
      { label: "Basketbol", value: "BASKETBALL" },
      { label: "Vücut Geliştirme", value: "BODYBUILDING" },
      { label: "Boks", value: "BOXING" },
      { label: "Satranç", value: "CHESS" },
      { label: "Amerikan Futbolu", value: "FOOTBALL (AMERICAN FOOTBALL)" },
      { label: "Futbol", value: "FOOTBALL (SOCCER)" },
      { label: "Kumar", value: "GAMBLING" },
      { label: "Golf", value: "GOLF" },
      { label: "Buz Hokeyi", value: "HOCKEY" },
      { label: "MMA / Kafes Dövüşü", value: "MMA" },
      { label: "Olimpiyatlar", value: "OLYMPICS" },
      { label: "Poker", value: "POKER" },
      { label: "Profesyonel Güreş", value: "PRO WRESTLING" },
      { label: "Sörf", value: "SURFING" },
      { label: "Yüzme", value: "SWIMMING" },
      { label: "Tenis", value: "TENNIS" },
      { label: "Yoga", value: "YOGA" },
      { label: "Avcılık", value: "HUNTING" },
      { label: "Koşu (Kros / Pist)", value: "RUNNING (CROSS-COUNTRY/TRACK)" },
    ],
  },
  {
    group: "Anlatım Teknikleri",
    options: [
      { label: "Belirsiz Son", value: "AMBIGUOUS ENDING" },
      { label: "Mutlu Son", value: "HAPPY ENDING" },
      { label: "Trajik Son", value: "TRAGIC ENDING" },
      { label: "Twist / Sürpriz Son", value: "TWIST/SURPRISE ENDING" },
      { label: "Dördüncü Duvarın Yıkılması", value: "BREAKING THE FOURTH WALL" },
      { label: "Geri Dönüş (Flashback)", value: "FLASHBACK" },
      { label: "Doğrusal Anlatı", value: "LINEAR NARRATIVE" },
      { label: "Anlatıcı", value: "NARRATOR" },
      { label: "Doğrusal Olmayan Anlatı", value: "NON-LINEAR NARRATIVE" },
      { label: "Kapalı Mekân / Tek Mekân", value: "CONTAINED ENVIRONS" },
      { label: "Dans / Dans Sahnesi", value: "DANCE/DANCING" },
      { label: "Efekt Odaklı", value: "EFFECTS DRIVEN" },
      { label: "Topluluk Oyuncu Kadrosu", value: "ENSEMBLE" },
      { label: "Buluntu Film (Found Footage)", value: "FOUND FOOTAGE" },
      { label: "Gizemli Nesne (Mystery Box / MacGuffin)", value: "MYSTERY BOX MACGUFFIN" },
      { label: "İleri Sıçrama (Flash-Forward)", value: "FLASH-FORWARD" },
      { label: "Paralel Hikâyeler", value: "PARALLEL STORYLINES" },
      { label: "İki Kişilik Hikâye (Two-Hander)", value: "TWO-HANDER" },
      { label: "Müzik Odaklı", value: "MUSIC-DRIVEN" },
      { label: "Seslendirme Anlatımı", value: "VOICE-OVER NARRATION" },
      { label: "Küçük Topluluk Kadro", value: "SMALL ENSEMBLE" },
      { label: "Geniş Topluluk Kadro", value: "LARGE ENSEMBLE" },
      { label: "Tek Bakış Açısı (POV)", value: "SINGULAR POV" },
      { label: "Yüksek Konsept", value: "HIGH CONCEPT" },
    ],
  },
  {
    group: "Alt Tür & Stil",
    options: [
      { label: "Taşlama / Satir", value: "SATIRE" },
      { label: "Slapstick (Fiziksel Komedi)", value: "SLAPSTICK" },
      { label: "Esrar / Stoner Komedisi", value: "STONER COMEDY" },
      { label: "Siberpunk", value: "CYBER PUNK" },
      { label: "Masal", value: "FAIRY TALE" },
      { label: "Kara Film (Film Noir)", value: "FILM NOIR" },
      { label: "Gotik", value: "GOTHIC" },
      { label: "Büyülü Gerçekçilik", value: "MAGICAL REALISM" },
      { label: "Sürrealizm", value: "SURREALISM" },
      { label: "Alternatif Tarih", value: "ALTERNATE HISTORY" },
      { label: "Biyografik Film (Biopic)", value: "BIOPIC" },
      { label: "Buddy Komedisi / İkili Komedi", value: "BUDDY COMEDY" },
      { label: "Tarihî Kurgu", value: "HISTORICAL FICTION" },
      { label: "Bağımsız Film (Indie)", value: "INDIE" },
      { label: "Sahte Belgesel (Mockumentary)", value: "MOCKUMENTARY" },
      { label: "Gerçek Suç", value: "TRUE CRIME" },
      { label: "Gözyaşı Dökertici (Tearjerker)", value: "TEARJERKER" },
      { label: "Kedi-Fare Oyunu", value: "CAT AND MOUSE" },
      { label: "İş Yeri Komedisi", value: "WORKPLACE COMEDY" },
      { label: "Grindhouse / B-Movie Tarzı", value: "GRINDHOUSE" },
      { label: "Absürt", value: "ABSURD" },
      { label: "Fars / Abartılı Komedi", value: "FARCE" },
      { label: "Cinayet Gizemi / Kim Yaptı?", value: "MURDER MYSTERY/WHODUNIT" },
      { label: "Parodi / Spoof", value: "SPOOF" },
    ],
  },
  {
    group: "Süper Güçler",
    options: [
      { label: "Süper Güçler", value: "SUPERPOWERS" },
      { label: "Uçma", value: "FLYING" },
      { label: "İyileştirme Gücü", value: "HEALING" },
      { label: "Zihin Kontrolü", value: "MIND CONTROL" },
      { label: "Şekil Değiştirme", value: "SHAPESHIFTING" },
      { label: "Telekinezi", value: "TELEKINESIS" },
      { label: "Görüşe Dayalı Güçler (Lazer vs.)", value: "VISION-BASED POWERS" },
    ],
  },
  {
    group: "İnsan Yaşam Alanları",
    options: [
      { label: "Uçak", value: "AIRPLANE" },
      { label: "Apartman", value: "APARTMENT" },
      { label: "Bina", value: "BUILDING" },
      { label: "Araba / Otobüs", value: "CAR/BUS" },
      { label: "Üniversite / Kampüs", value: "COLLEGE/UNIVERSITY" },
      { label: "Kurumsal Ofis", value: "CORPORATE OFFICE" },
      { label: "Mahkeme Salonu", value: "COURTROOM" },
      { label: "İlkokul", value: "ELEMENTARY SCHOOL" },
      { label: "Çiftlik / Ranch", value: "FARM/RANCH" },
      { label: "Lise", value: "HIGH SCHOOL" },
      { label: "Hastane", value: "HOSPITAL" },
      { label: "Otel / Pansiyon", value: "HOTEL/INN" },
      { label: "Ev", value: "HOUSE" },
      { label: "Kütüphane", value: "LIBRARY" },
      { label: "Gece Kulübü", value: "NIGHTCLUB" },
      { label: "Park", value: "PARK" },
      { label: "İbadet Yeri", value: "PLACE OF WORSHIP" },
      { label: "Hapishane / Cezaevi", value: "PRISON/JAIL" },
      { label: "Restoran", value: "RESTAURANT" },
      { label: "Yollar / Otoyollar", value: "ROADS/HIGHWAYS" },
      { label: "Kırsal", value: "RURAL" },
      { label: "Tek Mekân / Kapalı Mekân", value: "SINGLE/CONTAINED LOCATION" },
      { label: "Küçük Kasaba", value: "SMALL TOWN" },
      { label: "Spor Salonu / Arena", value: "SPORTS ARENA" },
      { label: "Banliyö", value: "SUBURBAN" },
      { label: "Tren", value: "TRAIN" },
      { label: "Kentsel / Şehir", value: "URBAN" },
    ],
  },
  {
    group: "Doğal Ortamlar",
    options: [
      { label: "Sahil / Plaj", value: "BEACH" },
      { label: "Okyanuslar", value: "OCEANS" },
      { label: "Göl / Nehir / Dere", value: "LAKES/RIVERS/STREAMS" },
      { label: "Çöl", value: "DESERT" },
      { label: "Orman", value: "FOREST" },
      { label: "Ada", value: "ISLAND" },
      { label: "Cangıl / Tropik Orman", value: "JUNGLE" },
      { label: "Dağlar", value: "MOUNTAINS" },
      { label: "Uzay Boşluğu", value: "OUTER SPACE" },
      { label: "Tropikler", value: "TROPICS" },
      { label: "Yeraltı", value: "UNDERGROUND" },
      { label: "Sualtı", value: "UNDERWATER" },
      { label: "Vahşi Doğa", value: "WILDERNESS" },
    ],
  },
  {
    group: "Fantastik Mekanlar",
    options: [
      { label: "Fantazi Dünyası", value: "FANTASY WORLD" },
      { label: "Cennet", value: "HEAVEN" },
      { label: "Cehennem", value: "HELL" },
      { label: "Araf", value: "PURGATORY" },
    ],
  },
  {
    group: "Kültürel Coğrafya / Alt Bölge",
    options: [
      { label: "ABD Kuzeydoğusu", value: "AMERICAN NORTHEAST" },
      { label: "ABD Pasifik Kuzeybatısı", value: "AMERICAN PACIFIC NORTHWEST" },
      { label: "ABD Ortabatı", value: "AMERICAN MIDWEST" },
      { label: "ABD Güneyi", value: "AMERICAN SOUTH" },
      { label: "ABD Güneybatısı", value: "AMERICAN SOUTHWEST" },
      { label: "ABD Batısı", value: "AMERICAN WEST" },
      { label: "Kaliforniya", value: "CALIFORNIA" },
      { label: "Karayipler", value: "CARIBBEAN" },
      { label: "Orta Afrika", value: "CENTRAL AFRICA" },
      { label: "Orta Amerika", value: "CENTRAL AMERICA" },
      { label: "Doğu Afrika", value: "EASTERN AFRICA" },
      { label: "Doğu Avrupa", value: "EASTERN EUROPE" },
      { label: "Florida", value: "FLORIDA" },
      { label: "Orta Doğu", value: "MIDDLE EAST" },
      { label: "Yeni İngiltere Bölgesi", value: "NEW ENGLAND" },
      { label: "New York (Eyalet/Bölge)", value: "NEW YORK" },
      { label: "Kuzey Afrika", value: "NORTHERN AFRICA" },
      { label: "İskandinavya", value: "SCANDINAVIA" },
      { label: "Sibirya", value: "SIBERIA" },
      { label: "Silikon Vadisi", value: "SILICON VALLEY" },
      { label: "Güneydoğu Asya", value: "SOUTHEAST ASIA" },
      { label: "Güney Afrika Bölgesi", value: "SOUTHERN AFRICA" },
      { label: "Teksas", value: "TEXAS" },
      { label: "Arktik", value: "THE ARCTIC" },
      { label: "Batı Afrika", value: "WESTERN AFRICA" },
      { label: "Batı Avrupa", value: "WESTERN EUROPE" },
    ],
  },
];

// =====================
// DÖNEM GRUPLARI (ERA)
// =====================

export const ERA_GROUPS: GroupedOptions[] = [
  {
    group: "Antik Çağ",
    options: [
      { label: "Antik Çağ", value: "ANTIQUITY" },
    ],
  },
  {
    group: "Gelecek",
    options: [
      { label: "Yakın Gelecek", value: "NEAR FUTURE" },
      { label: "Gelecek", value: "THE FUTURE" },
      { label: "Uzak Gelecek", value: "DISTANT FUTURE" },
      { label: "Kıyamet Sonrası", value: "POST-APOCALYPTIC" },
    ],
  },
  {
    group: "Diğer",
    options: [
      { label: "Belirtilmemiş / Genel Zaman", value: "UNSPECIFIED" },
      { label: "Alternatif Tarih / Gerçeklik", value: "ALTERNATIVE HISTORY/REALITY" },
    ],
  },
  {
    group: "Dönemler",
    options: [
      { label: "Orta Çağ", value: "MEDIEVAL" },
      { label: "Orta Çağ (Genel)", value: "MIDDLE AGES" },
      { label: "Rönesans", value: "RENAISSANCE" },
      { label: "1700’ler", value: "1700S" },
      { label: "1800’ler", value: "1800S" },
      { label: "1900’ler (Genel)", value: "1900S" },
      { label: "1910’lar", value: "1910S" },
      { label: "1920’ler", value: "1920S" },
      { label: "1930’lar", value: "1930S" },
      { label: "1940’lar", value: "1940S" },
      { label: "Sanayi Devrimi", value: "INDUSTRIAL REVOLUTION" },
      { label: "1. Dünya Savaşı Dönemi", value: "WORLD WAR I" },
      { label: "2. Dünya Savaşı Dönemi", value: "WORLD WAR II" },
      { label: "1950’ler", value: "1950S" },
      { label: "1960’lar", value: "1960S" },
      { label: "1970’ler", value: "1970S" },
      { label: "1980’ler", value: "1980S" },
      { label: "1990’lar", value: "1990S" },
      { label: "2000’ler", value: "2000S" },
      { label: "2010’lar", value: "2010S" },
      { label: "Y2K Dönemi", value: "Y2K" },
      { label: "Soğuk Savaş", value: "COLD WAR" },
    ],
  },
  {
    group: "Tarih Öncesi",
    options: [
      { label: "Tarih Öncesi", value: "PREHISTORIC" },
    ],
  },
  {
    group: "Günümüz",
    options: [
      { label: "Günümüz", value: "PRESENT DAY" },
    ],
  },
];

// =========================
// LOKASYON GRUPLARI
// =========================

export const LOCATION_GROUPS: GroupedOptions[] = [
  {
    group: "Alternatif Dünyalar & Uzay",
    options: [
      { label: "Alternatif Evren", value: "ALTERNATE UNIVERSE" },
      { label: "Dünya", value: "EARTH" },
      { label: "Mars", value: "MARS" },
      { label: "Ay", value: "MOON" },
      { label: "Gezegen / Galaksi", value: "PLANET/GALAXY" },
      { label: "Uzay Gemisi / Uzay", value: "SPACESHIP/SPACE" },
    ],
  },
  {
    group: "Şehirler",
    options: [
      { label: "Atlanta / ABD", value: "ATLANTA / USA" },
      { label: "Pekin / Çin", value: "BEIJING / CHINA" },
      { label: "Berlin / Almanya", value: "BERLIN / GERMANY" },
      { label: "Boston / ABD", value: "BOSTON / USA" },
      { label: "Brooklyn / ABD", value: "BROOKLYN / USA" },
      { label: "Buenos Aires / Arjantin", value: "BUENOS AIRES / ARGENTINA" },
      { label: "Chicago / ABD", value: "CHICAGO / USA" },
      { label: "Dubai / BAE", value: "DUBAI / UAE" },
      { label: "Edinburgh / İskoçya", value: "EDINBURGH / SCOTLAND" },
      { label: "Hong Kong / Çin", value: "HONG KONG / CHINA" },
      { label: "Las Vegas / ABD", value: "LAS VEGAS / USA" },
      { label: "Londra / İngiltere", value: "LONDON / ENGLAND" },
      { label: "Los Angeles / ABD", value: "LOS ANGELES / USA" },
      { label: "Melbourne / Avustralya", value: "MELBOURNE / AUSTRALIA" },
      { label: "Mexico City / Meksika", value: "MEXICO CITY / MEXICO" },
      { label: "Miami / ABD", value: "MIAMI / USA" },
      { label: "Moskova / Rusya", value: "MOSCOW / RUSSIA" },
      { label: "Mumbai / Hindistan", value: "MUMBAI / INDIA" },
      { label: "New York City / ABD", value: "NEW YORK CITY / USA" },
      { label: "Paris / Fransa", value: "PARIS / FRANCE" },
      { label: "Philadelphia / ABD", value: "PHILADELPHIA / USA" },
      { label: "Rio de Janeiro / Brezilya", value: "RIO DE JANEIRO / BRAZIL" },
      { label: "Roma / İtalya", value: "ROME / ITALY" },
      { label: "San Francisco / ABD", value: "SAN FRANCISCO / USA" },
      { label: "Seattle / ABD", value: "SEATTLE / USA" },
      { label: "Seul / Güney Kore", value: "SEOUL / SOUTH KOREA" },
      { label: "Şanghay / Çin", value: "SHANGHAI / CHINA" },
      { label: "Sidney / Avustralya", value: "SYDNEY / AUSTRALIA" },
      { label: "Tokyo / Japonya", value: "TOKYO / JAPAN" },
      { label: "Toronto / Kanada", value: "TORONTO / CANADA" },
      { label: "Washington DC / ABD", value: "WASHINGTON DC / USA" },
    ],
  },
  {
    group: "Kıtalar",
    options: [
      { label: "Afrika", value: "AFRICA" },
      { label: "Antarktika", value: "ANTARCTICA" },
      { label: "Asya", value: "ASIA" },
      { label: "Avrupa", value: "EUROPE" },
      { label: "Kuzey Amerika", value: "NORTH AMERICA" },
      { label: "Güney Amerika", value: "SOUTH AMERICA" },
    ],
  },
  {
    group: "Kıta + Ülke",
    options: [
      { label: "Avustralya", value: "AUSTRALIA" },
    ],
  },
  {
    group: "Ülkeler",
    options: [
      { label: "Afganistan", value: "AFGHANISTAN" },
      { label: "Brezilya", value: "BRAZIL" },
      { label: "Kanada", value: "CANADA" },
      { label: "Çin", value: "CHINA" },
      { label: "Kolombiya", value: "COLOMBIA" },
      { label: "Küba", value: "CUBA" },
      { label: "İngiltere", value: "ENGLAND" },
      { label: "Fransa", value: "FRANCE" },
      { label: "Almanya", value: "GERMANY" },
      { label: "Yunanistan", value: "GREECE" },
      { label: "Hindistan", value: "INDIA" },
      { label: "İran", value: "IRAN" },
      { label: "Irak", value: "IRAQ" },
      { label: "İrlanda", value: "IRELAND" },
      { label: "İsrail", value: "ISRAEL" },
      { label: "İtalya", value: "ITALY" },
      { label: "Japonya", value: "JAPAN" },
      { label: "Meksika", value: "MEXICO" },
      { label: "Yeni Zelanda", value: "NEW ZEALAND" },
      { label: "Nijerya", value: "NIGERIA" },
      { label: "Kuzey Kore", value: "NORTH KOREA" },
      { label: "Filipinler", value: "PHILIPPINES" },
      { label: "Polonya", value: "POLAND" },
      { label: "Rusya", value: "RUSSIA" },
      { label: "Singapur", value: "SINGAPORE" },
      { label: "Güney Afrika", value: "SOUTH AFRICA" },
      { label: "Güney Kore", value: "SOUTH KOREA" },
    ],
  },
  {
    group: "Kültürel Coğrafya / Alt Bölge",
    options: [
      { label: "ABD Kuzeydoğusu", value: "AMERICAN NORTHEAST" },
      { label: "ABD Pasifik Kuzeybatısı", value: "AMERICAN PACIFIC NORTHWEST" },
      { label: "ABD Ortabatı", value: "AMERICAN MIDWEST" },
      { label: "ABD Güneyi", value: "AMERICAN SOUTH" },
      { label: "ABD Güneybatısı", value: "AMERICAN SOUTHWEST" },
      { label: "ABD Batısı", value: "AMERICAN WEST" },
      { label: "Kaliforniya", value: "CALIFORNIA" },
      { label: "Karayipler", value: "CARIBBEAN" },
      { label: "Orta Afrika", value: "CENTRAL AFRICA" },
      { label: "Orta Amerika", value: "CENTRAL AMERICA" },
      { label: "Doğu Afrika", value: "EASTERN AFRICA" },
      { label: "Doğu Avrupa", value: "EASTERN EUROPE" },
      { label: "Florida", value: "FLORIDA" },
      { label: "Orta Doğu", value: "MIDDLE EAST" },
      { label: "Yeni İngiltere", value: "NEW ENGLAND" },
      { label: "New York Bölgesi", value: "NEW YORK" },
      { label: "Kuzey Afrika", value: "NORTHERN AFRICA" },
      { label: "İskandinavya", value: "SCANDINAVIA" },
      { label: "Sibirya", value: "SIBERIA" },
      { label: "Silikon Vadisi", value: "SILICON VALLEY" },
      { label: "Güneydoğu Asya", value: "SOUTHEAST ASIA" },
      { label: "Güney Afrika Bölgesi", value: "SOUTHERN AFRICA" },
      { label: "Teksas", value: "TEXAS" },
      { label: "Arktik Bölge", value: "THE ARCTIC" },
      { label: "Batı Afrika", value: "WESTERN AFRICA" },
      { label: "Batı Avrupa", value: "WESTERN EUROPE" },
    ],
  },
  {
    group: "İnsan Yaşam Alanları",
    options: [
      { label: "Uçak", value: "AIRPLANE" },
      { label: "Apartman", value: "APARTMENT" },
      { label: "Bina", value: "BUILDING" },
      { label: "Araba / Otobüs", value: "CAR/BUS" },
      { label: "Üniversite / Kampüs", value: "COLLEGE/UNIVERSITY" },
      { label: "Kurumsal Ofis", value: "CORPORATE OFFICE" },
      { label: "Mahkeme Salonu", value: "COURTROOM" },
      { label: "İlkokul", value: "ELEMENTARY SCHOOL" },
      { label: "Çiftlik / Ranch", value: "FARM/RANCH" },
      { label: "Lise", value: "HIGH SCHOOL" },
      { label: "Hastane", value: "HOSPITAL" },
      { label: "Otel / Pansiyon", value: "HOTEL/INN" },
      { label: "Ev", value: "HOUSE" },
      { label: "Kütüphane", value: "LIBRARY" },
      { label: "Gece Kulübü", value: "NIGHTCLUB" },
      { label: "Park", value: "PARK" },
      { label: "İbadet Yeri", value: "PLACE OF WORSHIP" },
      { label: "Hapishane / Cezaevi", value: "PRISON/JAIL" },
      { label: "Restoran", value: "RESTAURANT" },
      { label: "Yollar / Otoyollar", value: "ROADS/HIGHWAYS" },
      { label: "Kırsal", value: "RURAL" },
      { label: "Tek Mekân / Kapalı Mekân", value: "SINGLE/CONTAINED LOCATION" },
      { label: "Küçük Kasaba", value: "SMALL TOWN" },
      { label: "Spor Arena / Salon", value: "SPORTS ARENA" },
      { label: "Banliyö", value: "SUBURBAN" },
      { label: "Tren", value: "TRAIN" },
      { label: "Kentsel / Şehir", value: "URBAN" },
    ],
  },
  {
    group: "Doğal Ortamlar",
    options: [
      { label: "Sahil / Plaj", value: "BEACH" },
      { label: "Okyanuslar", value: "OCEANS" },
      { label: "Göl / Nehir / Dere", value: "LAKES/RIVERS/STREAMS" },
      { label: "Çöl", value: "DESERT" },
      { label: "Orman", value: "FOREST" },
      { label: "Ada", value: "ISLAND" },
      { label: "Cangıl / Tropik Orman", value: "JUNGLE" },
      { label: "Dağlar", value: "MOUNTAINS" },
      { label: "Uzay Boşluğu", value: "OUTER SPACE" },
      { label: "Tropikler", value: "TROPICS" },
      { label: "Yeraltı", value: "UNDERGROUND" },
      { label: "Sualtı", value: "UNDERWATER" },
      { label: "Vahşi Doğa", value: "WILDERNESS" },
    ],
  },
  {
    group: "Fantastik Mekanlar",
    options: [
      { label: "Fantazi Dünyası", value: "FANTASY WORLD" },
      { label: "Cennet", value: "HEAVEN" },
      { label: "Cehennem", value: "HELL" },
      { label: "Araf", value: "PURGATORY" },
    ],
  },
];

// ==========================
// İÇERİK UYARILARI
// ==========================

export const CONTENT_ADVISORY_TOPICS: LabeledOption[] = [
  { label: "Engelliliğe Karşı Ayrımcılık (Ableizm)", value: "ABLEISM" },
  { label: "Hayvana Şiddet", value: "ANIMAL ABUSE" },
  { label: "Hayvan Ölümü", value: "ANIMAL DEATH" },
  { label: "Çocuk İstismarı", value: "CHILD ABUSE" },
  { label: "Çocuk Ölümü", value: "DEATH OF CHILD" },
  { label: "Yeme Bozuklukları", value: "DISORDERED EATING" },
  { label: "Aile İçi Şiddet / Ev İçi İstismar", value: "DOMESTIC ABUSE" },
  { label: "Açık Seks / Grafik Çıplaklık", value: "EXPLICIT SEX/GRAPHIC NUDITY" },
  { label: "Aşırı Şiddet / Cinayet", value: "EXTREME VIOLENCE/MURDER" },
  { label: "Soykırım", value: "GENOCIDE" },
  { label: "Silahlı Şiddet / Okul Saldırısı", value: "GUN VIOLENCE/SCHOOL SHOOTING" },
  { label: "Nefret Suçları", value: "HATE CRIMES" },
  { label: "Homofobi / Transfobi", value: "HOMOPHOBIA/TRANSPHOBIA" },
  { label: "Ensest", value: "INCEST" },
  { label: "Kaçırma", value: "KIDNAPPING" },
  { label: "Ruh Sağlığı Problemleri", value: "MENTAL HEALTH ISSUES" },
  { label: "Askerî Çatışma / Muharebe", value: "MILITARY COMBAT" },
  { label: "Polis Şiddeti", value: "POLICE BRUTALITY" },
  {
    label: "Hamilelik ile İlgili Hassas Konular (Düşük, Kürtaj vb.)",
    value: "PREGNANCY-RELATED ISSUES (MISCARRIAGE, ABORTION, ETC.)",
  },
  { label: "Irkçılık / Irkçı Hakaretler", value: "RACISM/RACIAL SLURS" },
  { label: "Tecavüz / Cinsel Şiddet", value: "RAPE/SEXUAL VIOLENCE" },
  { label: "Dine Karşı Ayrımcılık", value: "RELIGIOUS DISCRIMINATION" },
  { label: "Kendine Zarar Verme", value: "SELF-HARM" },
  { label: "Cinsiyetçilik / Kadın Düşmanlığı", value: "SEXISM/MISOGYNY" },
];
